/**
 * Style Dictionary Configuration
 *
 * This configuration transforms design tokens from JSON source files
 * into multiple output formats:
 * 1. CSS Custom Properties (for vanilla CSS/Astro usage)
 * 2. JavaScript/ESM modules (for programmatic access in React/JS)
 */

export default {
  // Source token files
  source: ['src/tokens/source/**/*.json'],

  // Platform-specific outputs
  platforms: {
    // CSS Platform - Generates CSS Custom Properties
    css: {
      transformGroup: 'css',
      prefix: 'krado',
      buildPath: 'src/styles/tokens/',
      files: [
        {
          destination: 'generated.css',
          format: 'css/variables',
          options: {
            // Add --krado- prefix to all CSS variables
            selector: ':root',
            outputReferences: true
          }
        }
      ],
      options: {
        // Show file header with build info
        showFileHeader: true,
        fileHeader: (defaultMessage) => [
          '/**',
          ' * Krado UI - Generated Design Tokens',
          ' * DO NOT EDIT MANUALLY - This file is auto-generated by Style Dictionary',
          ' * Source: src/tokens/source/',
          ' * Generated: ' + new Date().toISOString(),
          ' */',
          ''
        ]
      }
    },

    // JavaScript/ESM Platform - Generates JavaScript module
    js: {
      transformGroup: 'js',
      buildPath: 'src/tokens/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
          options: {
            outputReferences: false,
            formatting: {
              prefix: '',
              commentStyle: 'short'
            }
          }
        }
      ]
    },

    // TypeScript Platform - Generates TypeScript definitions
    ts: {
      transformGroup: 'js',
      buildPath: 'src/tokens/',
      files: [
        {
          destination: 'tokens.d.ts',
          format: 'typescript/es6-declarations'
        }
      ]
    }
  },

  // Custom transforms
  transform: {
    // Custom transform to add --krado- prefix to CSS variable names
    'name/cti/krado-kebab': {
      type: 'name',
      transformer: (token) => {
        return '--krado-' + token.path.join('-');
      }
    }
  }
};
